# Generated by Django 5.0.3 on 2024-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyDuLichApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baidangtour',
            name='max',
            field=models.IntegerField(default=1),
        ),
    ]
