"""
Django settings for QuanLyDuLich project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hq=c_wh-*zsqfn0*l6%hzul62y=^xr(*b=qpn5q#lcm((o&@-v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}
ALLOWED_HOSTS = ['*']
import pymysql

pymysql.install_as_MySQLdb()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'QuanLyDuLichApp.apps.QuanlydulichappConfig',
    'drf_yasg',
    'rest_framework',
    'oauth2_provider',
    'ckeditor',
    'ckeditor_uploader',
    'corsheaders',
    'django.contrib.humanize',

]
# settings.py
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Hoặc có thể là 'django.contrib.sessions.backends.cache' hoặc các backend khác

CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = ["https://*", "http://*"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CSRF_COOKIE_NAME = 'csrftoken'  # Ensure this matches the cookie name set by Django
CSRF_COOKIE_SECURE = False  # Set to True if using HTTPS in production
CSRF_COOKIE_HTTPONLY = False  # Set to True for security, if necessary
CSRF_USE_SESSIONS = True  # Ensure CSRF tokens are managed via session

CKEDITOR_UPLOAD_PATH = "ckeditor/images"
CKEDITOR_VERSION = '5'
AUTH_USER_MODEL = 'QuanLyDuLichApp.User'

import cloudinary

cloudinary.config(
    cloud_name="depgwkadm",
    api_key="952231983342175",
    api_secret="Q2zQxgULDrl4SCt4-Qe-xg-buUM"
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]
WSGI_APPLICATION = 'QuanLyDuLich.wsgi.application'

ROOT_URLCONF = 'QuanLyDuLich.urls'
STATIC_URL = 'static/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'QuanLyDuLich.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST')
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CLIENT_ID = "N1kEnPaI19Cj4ntAm668vAlH9iT0nYcsDiCAvk3Q"
CLIENT_SECRET = "SKDX2OLdLIbPnkptjklXIKBPiymOEGvzopTLf1aVMf8dpU6VWCBVG7wDcL5YGSXHh2sc3aljVOoUG4tOWbNDoUu6XHIjk9bPnNrejwltaLNJyFtc7RgZ2qfpvWAiqBd5"
STRIPE_PUBLIC_KEY = "pk_test_51OQW5yB5fZWkJTYet5Arj2iLVSMxlENjaRB6P1nABaxIoaJQA9XbG5icHp92e6D6BmS6HTIS2uGhSkAHUUC0aXMc00rrxq7xCq"
STRIPE_SECRET_KEY = "sk_test_51OQW5yB5fZWkJTYeqtObrfSGlZvpiRzJbQGELcwzPP8ebl0b7MtmFos0cRpMzT6MpqLJG1qZvT6bEjSiRSVRBHTo00YB3EWc62"
SITE_URL = 'http://localhost:3000/'
STRIPE_SECRET_WEBHOOK = "whsec_6c13536560355363246520cf75f138a1441ad0c64df79cc4ba232f46d69eaf31"
# Client_id=qPHEZDqkKJluTH0QWv6SzCDLtYeKFUU48fN62Ked
# client_secret=M3ptxqUspelxVgAFukJwENlDCLHDueMQFueshaI2gChEmQgtoZ2FBTyV1YqrGIudt6wEpKZ92x79m48xZFozhhClaLsKF1Hlto3BCIORGEbd8hEY6l58cPBkxhcjxOHO
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tuannguyen2022002@gmail.com'
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST_PASSWORD = "cszm fick ykby zbjx"